### ISSUE TITLE
Possibly add the option to adjust and give CI

### ISSUE THREAD

**Issue by agdamsbo** [HannahJohns/genodds#1]
Hi Hannah. On the article published introducing the WinP (as you have described, basically the same as your gen.odds), there have been [written a comment (eLetter)](https://www.ahajournals.org/doi/10.1161/STROKEAHA.121.037744#comments) arguing that the general odds or winp could actually be adjusted and be provided with CIs using the following approaches:

> Secondly, contrary to what is stated by the authors, the WinP effect measure can easily be adjusted using inverse propensity score weighting2, where the probability estimates are weighted by the pairwise weight products. Confidence intervals for both the WinP and NNT effect measures can be estimated using bootstrap3 as long as the propensity scores are estimated separately for each bootstrap sample.

Having this option would make this approach a lot more interesting, but I believe it is beyond my own abilities. I found this article describing, what I think is very much the step-wise approach, so I'll give it a thorough look: https://www.r-bloggers.com/2017/04/exploring-propensity-score-matching-and-weighting/.

I would very much like to work with this analysis approach on a project I am presenting at ESOC, so we could discuss it there.

**Comment by HannahJohns** [comment]
Hi Andreas,

Let's discuss this further somewhere that's not a public github issue 😉 

If you don't have my email address you can grab it from the description file for any of my packages, otherwise I'll see you in a week

Cheers,

Hannah
